using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.IO;

namespace Riverbed.Pricing.Paint.Client
{
    public static class SiteMapPdfGenerator
    {
        public static byte[] GenerateSiteMapPdf()
        {
            // Set the QuestPDF license type to Community
            QuestPDF.Settings.License = LicenseType.Community;

            var siteMap = @"Essential Navigation (Site Map)

- / (Home)
- /dashboard (Dashboard)
- /companyhome (Company Home)
- /company-customer-list (Company Customer List)
- /companysettings (Company Settings Page)
- /companysettingscomponent (Company Settings Component)
- /companydefaultscomponent (Company Defaults Component)
- /company-projects (Company Projects Grid)
- /GlobalSettings (Global Settings)
- /pricing/projectentrymain/{{CustomerId}}/{{ProjectId}} and /pricing/projectentrymain/{{ProjectId}} (Project Entry Main)
- /reports/project-quote-report-main/{{ProjectGuid}} (Project Quote Report Main)

Account/Authentication:
- /Account/Login (Login)
- /Account/Register (Register)
- /Account/Manage (User Profile)
- /Account/Logout (Logout)

Other Navigable Components:
- /utils/fileuploader (File Uploader)
- /documentviewer (Document Viewer)
- /reportviewer (Report Viewer)
- /reportdesigner (Report Designer)

Notes:
- Main navigation is handled by NavMenu.razor using <NavLink>.
- Some pages require authorization ([Authorize] attribute).
- /reports/project-quote-report-main/{{ProjectGuid}} has its own sidebar for sub-navigation.
- The root / page redirects to /company-customer-list after authentication.
";

            var pdf = QuestPDF.Fluent.Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(30);
                    page.Size(PageSizes.A4);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(14));

                    page.Header().Text("Riverbed Pricing Paint - Site Map").SemiBold().FontSize(20).FontColor(Colors.Blue.Medium);
                    page.Content().PaddingVertical(10).Text(siteMap);
                    page.Footer().AlignCenter().Text(x =>
                    {
                        x.Span("Generated by GitHub Copilot");
                    });
                });
            });

            using var ms = new MemoryStream();
            pdf.GeneratePdf(ms);
            return ms.ToArray();
        }
    }
}
