// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Riverbed.Pricing.Paint.Shared.Data;

#nullable disable

namespace Riverbed.Pricing.Paint.Shared.Migrations
{
    [DbContext(typeof(PricingDbContext))]
    [Migration("20240218175355_AddMinorEntityNameChanges")]
    partial class AddMinorEntityNameChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.AreaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("AreaItemPrice")
                        .HasColumnType("real");

                    b.Property<int>("DifficultyLevelId")
                        .HasColumnType("int");

                    b.Property<int>("ItemCount")
                        .HasColumnType("int");

                    b.Property<int?>("ItemPaintId")
                        .HasColumnType("int");

                    b.Property<int>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PricingTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyLevelId");

                    b.HasIndex("ItemPaintId");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("PricingTypeId");

                    b.HasIndex("ProjectAreaId");

                    b.ToTable("AreaItems");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyDefaultsId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanySettingsId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CompanyCustomer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyCustomers");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CompanyDefaults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Baseboards")
                        .HasColumnType("bit");

                    b.Property<bool>("Ceilings")
                        .HasColumnType("bit");

                    b.Property<bool>("Doors")
                        .HasColumnType("bit");

                    b.Property<int>("PaintBrandId")
                        .HasColumnType("int");

                    b.Property<int>("PaintQualityId")
                        .HasColumnType("int");

                    b.Property<int>("PaintSheenId")
                        .HasColumnType("int");

                    b.Property<bool>("TrimDoors")
                        .HasColumnType("bit");

                    b.Property<bool>("Walls")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("CompanyDefaults");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CompanySettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("HourlyRate")
                        .HasColumnType("real");

                    b.Property<float>("LaborPercentage")
                        .HasColumnType("real");

                    b.Property<float>("MaterialPercentage")
                        .HasColumnType("real");

                    b.Property<float>("OverheadPercentage")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CompanySettings");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CustomersProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyCustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCodeId")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyCustomerId");

                    b.HasIndex("StatusCodeId");

                    b.ToTable("CustomersProject");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.DifficultyLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DifficultyLevelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DifficultyLevels");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.ItemPaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int?>("AreaItemId")
                        .HasColumnType("int");

                    b.Property<int>("Coats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gallons")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OverrideGallons")
                        .HasColumnType("int");

                    b.Property<bool>("OverrideGallonsFlag")
                        .HasColumnType("bit");

                    b.Property<int>("PaintTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaItemId");

                    b.HasIndex("PaintTypeId");

                    b.ToTable("ItemPaints");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.PaintBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaintBrandName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaintBrands");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.PaintQuality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaintQualityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaintQualities");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.PaintSheen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PaintSheenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PaintSheens");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.PaintType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoverageOneCoatSqFt")
                        .HasColumnType("int");

                    b.Property<int>("CoverageTwoCoatsSqFt")
                        .HasColumnType("int");

                    b.Property<int>("PaintSheenId")
                        .HasColumnType("int");

                    b.Property<string>("PaintTypeDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaintTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PricePerGallon")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PaintSheenId");

                    b.ToTable("PaintTypes");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.PricingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PricingTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PricingType");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.ProjectArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerProjectId")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsChangeOrder")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int?>("PictureId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectAreaName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectAreaNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerProjectId");

                    b.ToTable("ProjectAreas");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.ServiceTitanConnectionData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CompanyGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ServiceTitanApiClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("ServiceTitanApiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitanApiVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceTitanSecretKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceTitanConnectionDatas");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.StatusCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusCodeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusCodes");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.AreaItem", b =>
                {
                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.DifficultyLevel", "DifficultyLevel")
                        .WithMany()
                        .HasForeignKey("DifficultyLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.ItemPaint", "ItemPaint")
                        .WithMany()
                        .HasForeignKey("ItemPaintId");

                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.PricingType", "PricingType")
                        .WithMany()
                        .HasForeignKey("PricingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.ProjectArea", "ProjectArea")
                        .WithMany("AreaItems")
                        .HasForeignKey("ProjectAreaId");

                    b.Navigation("DifficultyLevel");

                    b.Navigation("ItemPaint");

                    b.Navigation("ItemType");

                    b.Navigation("PricingType");

                    b.Navigation("ProjectArea");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CompanyCustomer", b =>
                {
                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.Company", "Company")
                        .WithMany("CompanyCustomers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CustomersProject", b =>
                {
                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.CompanyCustomer", "CompanyCustomer")
                        .WithMany("CustomerProjects")
                        .HasForeignKey("CompanyCustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.StatusCode", "StatusCode")
                        .WithMany()
                        .HasForeignKey("StatusCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyCustomer");

                    b.Navigation("StatusCode");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.ItemPaint", b =>
                {
                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.AreaItem", null)
                        .WithMany("ItemPaints")
                        .HasForeignKey("AreaItemId");

                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.PaintType", "PaintType")
                        .WithMany()
                        .HasForeignKey("PaintTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaintType");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.PaintType", b =>
                {
                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.PaintSheen", "PaintSheen")
                        .WithMany()
                        .HasForeignKey("PaintSheenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaintSheen");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.ProjectArea", b =>
                {
                    b.HasOne("Riverbed.Pricing.Paint.Shared.Entities.CustomersProject", "CustomersProject")
                        .WithMany("ProjectAreas")
                        .HasForeignKey("CustomerProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomersProject");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.AreaItem", b =>
                {
                    b.Navigation("ItemPaints");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.Company", b =>
                {
                    b.Navigation("CompanyCustomers");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CompanyCustomer", b =>
                {
                    b.Navigation("CustomerProjects");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.CustomersProject", b =>
                {
                    b.Navigation("ProjectAreas");
                });

            modelBuilder.Entity("Riverbed.Pricing.Paint.Shared.Entities.ProjectArea", b =>
                {
                    b.Navigation("AreaItems");
                });
#pragma warning restore 612, 618
        }
    }
}
